/**
 * Dữ liệu chuyên khoa với keywords, synonyms và weights
 */

module.exports = {
  'than_kinh': {
    name: 'Thần kinh',
    icon: '🧠',
    keywords: [
      { word: 'đau đầu', weight: 10, synonyms: ['nhức đầu', 'đầu đau', 'dau dau', 'đau đầu dữ dội'] },
      { word: 'chóng mặt', weight: 9, synonyms: ['hoa mắt', 'choáng', 'choang', 'chong mat', 'hoa mat', 'váng đầu'] },
      { word: 'mất ngủ', weight: 8, synonyms: ['khó ngủ', 'không ngủ được', 'mat ngu', 'kho ngu', 'thức đêm', 'mất giấc'] },
      { word: 'đau nửa đầu', weight: 10, synonyms: ['migraine', 'đau nửa đầu', 'đau đầu một bên', 'nhức nửa đầu'] },
      { word: 'run tay chân', weight: 9, synonyms: ['run tay', 'run chân', 'run rẩy', 'rung', 'run liên tục'] },
      { word: 'tê tay chân', weight: 9, synonyms: ['tê bì', 'tê tay', 'tê chân', 'tê liệt', 'tê mỏi'] },
      { word: 'co giật', weight: 10, synonyms: ['giật mình', 'co cứng', 'co thắt', 'giật cơ', 'co giật toàn thân'] },
      { word: 'mất trí nhớ', weight: 9, synonyms: ['quên', 'hay quên', 'suy giảm trí nhớ', 'mất trí', 'không nhớ'] },
      { word: 'hay quên', weight: 8, synonyms: ['quên lãng', 'hay quên việc', 'dễ quên', 'quên nhanh'] },
      { word: 'mệt mỏi thần kinh', weight: 8, synonyms: ['mệt mỏi', 'mệt', 'mỏi', 'met moi', 'uể oải', 'kiệt sức'] },
      { word: 'khó tập trung', weight: 8, synonyms: ['không tập trung', 'mất tập trung', 'không chú ý', 'xao lãng'] },
      { word: 'stress kéo dài', weight: 8, synonyms: ['stress', 'căng thẳng', 'lo âu', 'lo lắng', 'canh thang', 'lo au', 'stress mãn tính'] },
      { word: 'đau dây thần kinh', weight: 10, synonyms: ['đau thần kinh', 'viêm dây thần kinh', 'đau dây', 'tổn thương thần kinh'] },
      { word: 'mất thăng bằng', weight: 9, synonyms: ['loạng choạng', 'đi không vững', 'mất cân bằng', 'không giữ thăng bằng'] },
      { word: 'hoa mắt', weight: 8, synonyms: ['mờ mắt', 'nhìn mờ', 'chóng mặt', 'hoa mắt chóng mặt'] },
      { word: 'ngất xỉu', weight: 10, synonyms: ['ngất', 'xỉu', 'bất tỉnh', 'mất ý thức', 'choáng váng'] },
      { word: 'yếu cơ', weight: 9, synonyms: ['yếu tay chân', 'cơ yếu', 'mất sức', 'không có sức', 'teo cơ'] },
      { word: 'liệt mặt', weight: 10, synonyms: ['méo mặt', 'liệt nửa mặt', 'mặt méo', 'liệt dây thần kinh mặt'] },
      { word: 'đau cổ vai gáy', weight: 8, synonyms: ['đau cổ', 'đau vai', 'đau gáy', 'nhức cổ vai', 'cứng cổ'] },
      { word: 'đau lưng thần kinh', weight: 9, synonyms: ['đau lưng', 'nhức lưng', 'đau thần kinh tọa', 'đau dây thần kinh lưng'] },
      { word: 'dị cảm', weight: 8, synonyms: ['cảm giác lạ', 'tê buốt', 'châm chích', 'kiến bò', 'ngứa ran'] },
      { word: 'rối loạn giấc ngủ', weight: 8, synonyms: ['ngủ không ngon', 'ngủ không sâu', 'thức giấc nhiều', 'mất ngủ'] },
      { word: 'căng thẳng thần kinh', weight: 8, synonyms: ['căng thẳng', 'stress', 'lo âu', 'bồn chồn', 'bất an'] },
      { word: 'lo âu', weight: 8, synonyms: ['lo lắng', 'lo sợ', 'bồn chồn', 'hồi hộp', 'bất an'] },
      { word: 'trầm cảm nhẹ', weight: 8, synonyms: ['trầm cảm', 'buồn chán', 'u sầu', 'tram cam', 'chán nản'] },
      { word: 'động kinh', weight: 10, synonyms: ['co giật', 'giật cơ', 'động kinh toàn thể', 'cơn động kinh'] },
      { word: 'khó nói', weight: 9, synonyms: ['nói khó', 'nói ngọng', 'nói lắp', 'khó phát âm', 'nói không rõ'] },
      { word: 'méo miệng', weight: 10, synonyms: ['miệng méo', 'liệt mặt', 'mặt méo', 'méo mồm'] },
      { word: 'tay chân yếu', weight: 9, synonyms: ['yếu tay chân', 'tay yếu', 'chân yếu', 'mất sức', 'liệt nhẹ'] },
      { word: 'rối loạn cảm giác', weight: 8, synonyms: ['mất cảm giác', 'tê liệt', 'dị cảm', 'cảm giác lạ', 'giảm cảm giác'] }
    ]
  },
  'xuong_khop': {
    name: 'Cơ xương khớp',
    icon: '🦴',
    keywords: [
      { word: 'đau lưng', weight: 10, synonyms: ['nhức lưng', 'dau lung', 'lung dau', 'lưng đau', 'đau thắt lưng'] },
      { word: 'đau cổ vai gáy', weight: 9, synonyms: ['đau cổ', 'đau vai', 'đau gáy', 'nhức cổ vai', 'cứng cổ', 'mỏi vai gáy'] },
      { word: 'đau khớp gối', weight: 10, synonyms: ['đau gối', 'nhức gối', 'gối đau', 'dau goi', 'đau đầu gối'] },
      { word: 'đau vai', weight: 9, synonyms: ['nhức vai', 'vai đau', 'dau vai', 'đau khớp vai'] },
      { word: 'đau cột sống', weight: 9, synonyms: ['đau lưng', 'nhức cột sống', 'cột sống đau', 'đau sống lưng'] },
      { word: 'tê tay chân', weight: 8, synonyms: ['tê bì', 'tê tay', 'tê chân', 'tê liệt', 'tê mỏi'] },
      { word: 'cứng khớp', weight: 9, synonyms: ['khớp cứng', 'khớp không mềm', 'cứng đơ', 'khó cử động khớp'] },
      { word: 'đau cơ', weight: 8, synonyms: ['nhức cơ', 'cơ đau', 'dau co', 'đau bắp thịt'] },
      { word: 'nhức mỏi xương khớp', weight: 8, synonyms: ['mỏi xương', 'nhức xương', 'mỏi khớp', 'nhức khớp', 'xương khớp đau'] },
      { word: 'sưng khớp', weight: 9, synonyms: ['khớp sưng', 'sưng đau khớp', 'phù khớp', 'khớp to'] },
      { word: 'viêm khớp', weight: 10, synonyms: ['viem khop', 'khớp viêm', 'viêm đau khớp', 'viêm nhiều khớp'] },
      { word: 'khó vận động', weight: 9, synonyms: ['khó cử động', 'khó di chuyển', 'hạn chế vận động', 'cứng đơ'] },
      { word: 'đau thắt lưng', weight: 10, synonyms: ['thắt lưng đau', 'đau lưng dưới', 'đau vùng thắt lưng'] },
      { word: 'đau bàn chân', weight: 8, synonyms: ['bàn chân đau', 'nhức bàn chân', 'đau gót chân', 'đau mu bàn chân'] },
      { word: 'đau bàn tay', weight: 8, synonyms: ['bàn tay đau', 'nhức bàn tay', 'đau cổ tay', 'đau ngón tay'] },
      { word: 'chuột rút', weight: 8, synonyms: ['co cứng cơ', 'co thắt cơ', 'chuột rút chân', 'chuột rút tay'] },
      { word: 'yếu cơ', weight: 8, synonyms: ['yếu tay chân', 'cơ yếu', 'mất sức', 'không có sức', 'teo cơ'] },
      { word: 'khớp phát tiếng kêu', weight: 7, synonyms: ['khớp kêu', 'khớp kêu lục cục', 'khớp kêu răng rắc', 'tiếng kêu khớp'] },
      { word: 'đau khi đi lại', weight: 9, synonyms: ['đau khi đi', 'đau khi bước', 'khó đi lại', 'đau khi vận động'] },
      { word: 'đau đầu gối khi leo cầu thang', weight: 9, synonyms: ['đau gối leo cầu thang', 'gối đau khi lên xuống cầu thang', 'đau khi leo thang'] },
      { word: 'cứng cổ', weight: 8, synonyms: ['cổ cứng', 'cổ không quay được', 'đau cứng cổ', 'khó quay cổ'] },
      { word: 'đau hông', weight: 9, synonyms: ['nhức hông', 'hông đau', 'đau khớp hông', 'đau xương hông'] },
      { word: 'đau xương', weight: 9, synonyms: ['nhức xương', 'xương đau', 'đau nhức xương', 'xương bị đau'] },
      { word: 'sưng đau cơ', weight: 8, synonyms: ['cơ sưng', 'sưng cơ', 'viêm cơ', 'đau và sưng cơ'] },
      { word: 'mỏi vai gáy', weight: 8, synonyms: ['vai gáy mỏi', 'nhức vai gáy', 'mỏi cổ vai', 'vai gáy nặng'] },
      { word: 'thoái hóa khớp', weight: 10, synonyms: ['thoái hóa', 'thoai hoa', 'khớp thoái hóa', 'thoái hóa cột sống'] },
      { word: 'đau dây thần kinh tọa', weight: 10, synonyms: ['đau thần kinh tọa', 'tọa cốt thần kinh', 'đau từ lưng xuống chân'] },
      { word: 'khó cúi người', weight: 8, synonyms: ['không cúi được', 'cúi khó', 'đau khi cúi', 'cứng lưng'] },
      { word: 'khó đứng lâu', weight: 8, synonyms: ['không đứng lâu được', 'đau khi đứng lâu', 'mỏi khi đứng'] },
      { word: 'đau khi vận động', weight: 9, synonyms: ['đau khi cử động', 'đau khi hoạt động', 'đau khi di chuyển', 'vận động đau'] }
    ]
  },
  'tim_mach': {
    name: 'Tim mạch',
    icon: '❤️',
    keywords: [
      { word: 'đau ngực', weight: 10, synonyms: ['tức ngực', 'ngực đau', 'dau nguc', 'nhức ngực', 'đau vùng ngực'] },
      { word: 'tức ngực', weight: 10, synonyms: ['ngực tức', 'nghẹt ngực', 'ngực nghẹt', 'căng tức ngực'] },
      { word: 'khó thở', weight: 10, synonyms: ['thở khó', 'kho tho', 'thở gấp', 'hụt hơi', 'thở nhanh'] },
      { word: 'tim đập nhanh', weight: 9, synonyms: ['hồi hộp', 'tim nhanh', 'đánh trống ngực', 'tim đập mạnh', 'nhịp tim nhanh'] },
      { word: 'tim đập chậm', weight: 9, synonyms: ['tim chậm', 'nhịp tim chậm', 'tim đập yếu', 'tim đập ít'] },
      { word: 'hồi hộp', weight: 8, synonyms: ['tim đập nhanh', 'tim hồi hộp', 'hồi hộp tim', 'tim nhanh'] },
      { word: 'chóng mặt', weight: 8, synonyms: ['hoa mắt', 'choáng', 'choang', 'chong mat', 'hoa mat', 'váng đầu'] },
      { word: 'mệt mỏi', weight: 8, synonyms: ['mệt', 'mỏi', 'met moi', 'uể oải', 'kiệt sức'] },
      { word: 'đau tim', weight: 10, synonyms: ['nhức tim', 'tim đau', 'dau tim', 'đau vùng tim', 'đau tức vùng tim'] },
      { word: 'huyết áp cao', weight: 10, synonyms: ['huyết áp', 'cao huyết áp', 'huyet ap', 'huyệt áp cao', 'tăng huyết áp'] },
      { word: 'huyết áp thấp', weight: 9, synonyms: ['hạ huyết áp', 'huyết áp thấp', 'huyết áp giảm', 'huyết áp yếu'] },
      { word: 'đau ngực khi vận động', weight: 10, synonyms: ['đau ngực khi gắng sức', 'đau ngực khi hoạt động', 'đau khi vận động'] },
      { word: 'khó thở khi nằm', weight: 9, synonyms: ['thở khó khi nằm', 'khó thở ban đêm', 'thở khó khi ngủ'] },
      { word: 'phù chân', weight: 9, synonyms: ['sưng chân', 'chân sưng', 'phù bàn chân', 'chân phù'] },
      { word: 'đau vai trái', weight: 9, synonyms: ['vai trái đau', 'nhức vai trái', 'đau vai bên trái'] },
      { word: 'tê tay trái', weight: 9, synonyms: ['tay trái tê', 'tê bì tay trái', 'tê cánh tay trái'] },
      { word: 'ngất xỉu', weight: 10, synonyms: ['ngất', 'xỉu', 'bất tỉnh', 'mất ý thức', 'choáng váng'] },
      { word: 'tim đập không đều', weight: 9, synonyms: ['nhịp tim không đều', 'loạn nhịp tim', 'tim đập bất thường', 'rối loạn nhịp tim'] },
      { word: 'đau tức vùng tim', weight: 10, synonyms: ['tức vùng tim', 'đau vùng tim', 'tức ngực trái', 'đau tim'] },
      { word: 'thở gấp', weight: 9, synonyms: ['thở nhanh', 'thở hổn hển', 'thở dốc', 'thở mệt'] },
      { word: 'mệt khi leo cầu thang', weight: 9, synonyms: ['mệt khi lên cầu thang', 'khó thở khi leo thang', 'mệt khi vận động'] },
      { word: 'đau lan lên cổ', weight: 9, synonyms: ['đau cổ', 'đau lan ra cổ', 'đau từ ngực lên cổ', 'đau lan vai cổ'] },
      { word: 'đổ mồ hôi lạnh', weight: 9, synonyms: ['ra mồ hôi lạnh', 'toát mồ hôi lạnh', 'mồ hôi lạnh', 'đổ mồ hôi'] },
      { word: 'đau ngực kéo dài', weight: 10, synonyms: ['đau ngực dai dẳng', 'đau ngực lâu', 'đau ngực không ngớt'] },
      { word: 'cảm giác hụt hơi', weight: 9, synonyms: ['hụt hơi', 'thiếu hơi', 'khó thở', 'thở không đủ'] },
      { word: 'mệt tim', weight: 9, synonyms: ['suy tim', 'yếu tim', 'tim yếu', 'tim mệt', 'met tim'] },
      { word: 'đau vùng ngực trái', weight: 10, synonyms: ['đau ngực trái', 'ngực trái đau', 'đau bên trái ngực'] },
      { word: 'nhịp tim bất thường', weight: 9, synonyms: ['tim đập bất thường', 'loạn nhịp', 'rối loạn nhịp tim', 'tim không đều'] },
      { word: 'căng tức ngực', weight: 9, synonyms: ['ngực căng', 'tức ngực', 'ngực đau', 'căng vùng ngực'] },
      { word: 'khó thở về đêm', weight: 9, synonyms: ['khó thở ban đêm', 'thở khó đêm', 'khó thở khi ngủ', 'thở khó về đêm'] }
    ]
  },
  'tieu_hoa': {
    name: 'Tiêu hóa',
    icon: '🍽️',
    keywords: [
      { word: 'đau bụng', weight: 10, synonyms: ['nhức bụng', 'bụng đau', 'dau bung', 'đau dạ dày', 'đau bao tử'] },
      { word: 'đầy hơi', weight: 9, synonyms: ['chướng bụng', 'đầy bụng', 'day hoi', 'bụng đầy', 'bụng phình'] },
      { word: 'khó tiêu', weight: 9, synonyms: ['kho tieu', 'khó tiêu hóa', 'ăn không tiêu', 'tiêu hóa kém'] },
      { word: 'buồn nôn', weight: 9, synonyms: ['nôn', 'ói', 'muốn nôn', 'buon non', 'cảm giác nôn'] },
      { word: 'nôn ói', weight: 9, synonyms: ['nôn', 'ói', 'nôn mửa', 'ói mửa', 'nôn ra'] },
      { word: 'tiêu chảy', weight: 10, synonyms: ['ỉa chảy', 'đi ngoài', 'tieu chay', 'tiêu lỏng', 'đi ngoài nhiều'] },
      { word: 'táo bón', weight: 9, synonyms: ['táo', 'tao bon', 'khó đi ngoài', 'bí đại tiện', 'táo lâu ngày'] },
      { word: 'đau dạ dày', weight: 10, synonyms: ['dạ dày đau', 'đau bao tử', 'nhức dạ dày', 'đau thượng vị'] },
      { word: 'ợ chua', weight: 8, synonyms: ['ợ', 'ợ hơi chua', 'o chua', 'ợ trào ngược'] },
      { word: 'ợ nóng', weight: 8, synonyms: ['ợ', 'trào ngược', 'o nong', 'ợ hơi nóng', 'nóng ngực'] },
      { word: 'chướng bụng', weight: 9, synonyms: ['đầy hơi', 'bụng chướng', 'bụng căng', 'bụng phình'] },
      { word: 'đi ngoài ra máu', weight: 10, synonyms: ['phân có máu', 'đại tiện ra máu', 'máu trong phân', 'đi cầu ra máu'] },
      { word: 'phân đen', weight: 10, synonyms: ['đại tiện đen', 'phân màu đen', 'phân sẫm', 'phân đen sì'] },
      { word: 'đau bụng dưới', weight: 9, synonyms: ['đau vùng chậu', 'dau bung duoi', 'đau hạ vị', 'đau bụng phía dưới'] },
      { word: 'viêm đại tràng', weight: 10, synonyms: ['đại tràng viêm', 'viêm ruột', 'viêm đại tràng cấp'] },
      { word: 'viêm dạ dày', weight: 10, synonyms: ['dạ dày viêm', 'viem da day', 'viêm bao tử', 'viêm loét dạ dày'] },
      { word: 'co thắt bụng', weight: 8, synonyms: ['co bụng', 'bụng co', 'co cứng bụng', 'cơn co bụng'] },
      { word: 'khó nuốt', weight: 8, synonyms: ['nuốt khó', 'khó nuốt nước', 'đau khi nuốt', 'nuốt vướng'] },
      { word: 'đau khi ăn', weight: 8, synonyms: ['ăn đau', 'đau khi ăn uống', 'ăn bị đau', 'đau sau khi ăn'] },
      { word: 'ăn không ngon', weight: 7, synonyms: ['chán ăn', 'biếng ăn', 'không thèm ăn', 'kém ăn'] },
      { word: 'sụt cân', weight: 8, synonyms: ['giảm cân', 'sut can', 'gầy', 'nhẹ cân', 'giảm cân nhanh'] },
      { word: 'mệt mỏi tiêu hóa', weight: 7, synonyms: ['mệt mỏi', 'mệt', 'mỏi', 'met moi', 'uể oải'] },
      { word: 'đau gan', weight: 9, synonyms: ['gan đau', 'nhức gan', 'đau vùng gan', 'đau hạ sườn phải'] },
      { word: 'vàng da', weight: 9, synonyms: ['da vàng', 'vàng mắt', 'vàng da mắt', 'da bị vàng'] },
      { word: 'đắng miệng', weight: 7, synonyms: ['miệng đắng', 'miệng bị đắng', 'vị đắng', 'cảm giác đắng'] },
      { word: 'đau quanh rốn', weight: 8, synonyms: ['đau rốn', 'rốn đau', 'đau vùng rốn', 'nhức quanh rốn'] },
      { word: 'đi ngoài nhiều lần', weight: 9, synonyms: ['tiêu chảy', 'đi ngoài liên tục', 'đi cầu nhiều', 'đại tiện nhiều'] },
      { word: 'táo bón kéo dài', weight: 9, synonyms: ['táo mãn tính', 'táo lâu ngày', 'táo dai dẳng', 'bí đại tiện lâu'] },
      { word: 'nóng rát dạ dày', weight: 9, synonyms: ['dạ dày nóng', 'rát dạ dày', 'nóng bao tử', 'rát bao tử'] },
      { word: 'trào ngược dạ dày', weight: 9, synonyms: ['trào ngược', 'ợ nóng', 'ợ chua', 'trào ngược thực quản'] }
    ]
  },
  'ho_hap': {
    name: 'Hô hấp',
    icon: '🫁',
    keywords: [
      { word: 'ho', weight: 10, synonyms: ['ho khan', 'ho có đờm', 'ho đờm', 'ho lâu ngày', 'ho nhiều'] },
      { word: 'ho khan', weight: 9, synonyms: ['ho khô', 'ho không đờm', 'ho khạc', 'ho liên tục'] },
      { word: 'ho có đờm', weight: 9, synonyms: ['ho đờm', 'ho bị đờm', 'ho ra đờm', 'ho có đàm'] },
      { word: 'khó thở', weight: 10, synonyms: ['thở khó', 'kho tho', 'thở gấp', 'hụt hơi', 'thở nhanh', 'khó hít thở'] },
      { word: 'đau họng', weight: 9, synonyms: ['họng đau', 'dau hong', 'viêm họng', 'sưng họng', 'nhức họng'] },
      { word: 'viêm họng', weight: 9, synonyms: ['họng viêm', 'viem hong', 'họng sưng', 'họng đỏ'] },
      { word: 'nghẹt mũi', weight: 8, synonyms: ['ngạt mũi', 'tắc mũi', 'nghet mui', 'mũi tắc', 'mũi bị nghẹt'] },
      { word: 'sổ mũi', weight: 8, synonyms: ['chảy nước mũi', 'so mui', 'mũi chảy', 'chảy mũi'] },
      { word: 'hắt hơi', weight: 7, synonyms: ['hắt xì', 'hắt hơi liên tục', 'hắt hơi nhiều', 'hắt xì hơi'] },
      { word: 'đau ngực khi thở', weight: 9, synonyms: ['ngực đau khi thở', 'đau ngực', 'thở đau ngực', 'đau khi hít thở'] },
      { word: 'thở khò khè', weight: 9, synonyms: ['khò khè', 'thở rít', 'thở có tiếng', 'thở khó'] },
      { word: 'tức ngực', weight: 9, synonyms: ['ngực tức', 'nghẹt ngực', 'ngực nghẹt', 'khó thở ngực'] },
      { word: 'viêm phế quản', weight: 10, synonyms: ['phế quản viêm', 'viêm phế quản cấp', 'viêm phế quản mãn'] },
      { word: 'viêm phổi', weight: 10, synonyms: ['viem phoi', 'phổi viêm', 'nhiễm trùng phổi', 'viêm phổi cấp'] },
      { word: 'hen suyễn', weight: 10, synonyms: ['hen', 'suyễn', 'hen suyen', 'hen phế quản', 'bệnh hen'] },
      { word: 'ho kéo dài', weight: 9, synonyms: ['ho mãn tính', 'ho lâu ngày', 'ho không khỏi', 'ho dai dẳng'] },
      { word: 'khàn tiếng', weight: 8, synonyms: ['tiếng khàn', 'khàn giọng', 'giọng khàn', 'nói khàn'] },
      { word: 'mất tiếng', weight: 9, synonyms: ['mất giọng', 'không nói được', 'câm tiếng', 'tiếng bị mất'] },
      { word: 'khó nuốt', weight: 8, synonyms: ['nuốt khó', 'khó nuốt nước', 'đau khi nuốt', 'nuốt vướng'] },
      { word: 'đau khi nuốt', weight: 8, synonyms: ['nuốt đau', 'đau nuốt', 'đau họng khi nuốt', 'nuốt bị đau'] },
      { word: 'thở gấp', weight: 9, synonyms: ['thở nhanh', 'thở hổn hển', 'thở dốc', 'thở mệt'] },
      { word: 'ho ra máu', weight: 10, synonyms: ['ho máu', 'khạc máu', 'ho có máu', 'đờm có máu'] },
      { word: 'đờm nhiều', weight: 8, synonyms: ['nhiều đờm', 'đàm nhiều', 'đờm đặc', 'đờm vàng', 'đờm xanh'] },
      { word: 'viêm xoang', weight: 9, synonyms: ['viem xoang', 'xoang viêm', 'đau xoang', 'viêm xoang mũi'] },
      { word: 'chảy nước mũi', weight: 8, synonyms: ['sổ mũi', 'mũi chảy nước', 'chảy mũi', 'nước mũi chảy'] },
      { word: 'viêm amidan', weight: 9, synonyms: ['viem amidan', 'amidan sưng', 'sưng amidan', 'amidan viêm'] },
      { word: 'cảm lạnh', weight: 8, synonyms: ['cảm', 'cúm', 'cam cum', 'cảm cúm', 'bị cảm'] },
      { word: 'sốt kèm ho', weight: 9, synonyms: ['sốt và ho', 'ho và sốt', 'sốt ho', 'ho có sốt'] },
      { word: 'mệt khi hít thở', weight: 8, synonyms: ['mệt khi thở', 'thở mệt', 'hít thở mệt', 'khó thở mệt'] },
      { word: 'dị ứng hô hấp', weight: 9, synonyms: ['dị ứng đường hô hấp', 'dị ứng phổi', 'dị ứng mũi họng', 'viêm mũi dị ứng'] }
    ]
  }
};
